### ISSUE TITLE
Android N still  failing with apk install using custom external directory 

### ISSUE THREAD

**Issue by mamcgree** [darryncampbell/darryncampbell-cordova-plugin-intent#10]
Greetings Darryn..
I'm Still having issue with Android N when installing apk from external file location.
I create my file paths using variables from the cordova file plugin.
eg : cordova.file.externalApplicationStorageDirectory + "downloads/my.apk";
will return url "file:///storage/emulated/0/Android/data/com.mycompany.myapp/downloads/my.apk"
Which allows me to install the apk using "window.plugins.intentShim.startActivity"
It fails on android N..
If you change line 92 in your intentShim.java
File uriAsFile = new File(Environment.getExternalStorageDirectory(), fileName);
to
File uriAsFile = new File(fileName);
It then works perfectly for any custom location
Currently it fails.

Thank you in advance for any consideration

Cheers..
Mark

**Comment by darryncampbell** [comment]
Hi, what device are you using?  I'm sure when i tested on my Nexus 6P I got an error when I called getUriForFile() after declaring the file with file:///.  That's running 7.1.  Or perhaps it works for you because the apk is located in your application's sandbox folder.  I'll do a bit more testing when I get a chance.

**Comment by mamcgree** [comment]
You cannot declare with file:///..
Your code is correct except for line 92..  at that point you have already stripped off the file:// out of the fileName.
You just need to change 
File uriAsFile = new File(Environment.getExternalStorageDirectory(), fileName);
to
File uriAsFile = new File(fileName);

Cheers..

**Comment by darryncampbell** [comment]
Oh I see!  Thanks, I'll take a look.  I like the thought of using the https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/ plugin for the external directory.

**Comment by darryncampbell** [comment]
Yes that's much better.  I changed the logic and updated the version to 0.0.13.  Thanks.
