### ISSUE TITLE
wrong way inside the whatsapp

### ISSUE THREAD

**Issue by amnzera** [darryncampbell/darryncampbell-cordova-plugin-intent#112]
guys into the whatsapp , i try share document for my app and show this path:
"content://com.whatsapp.provider.media/item/1f1c0bd0-c811-4958-94d8-063c31fe4a1f"
this path not working.

in file explorer returns this path:
"content://com.mi.android.globalFileexplorer.myprovider/external_files/WhatsApp/Media/WhatsApp%20Documents/b1313e3e52a4b08d6cb0a9dddb35549f.pdf"

this path works fine

how resolve this into whatsapp?

resolveNativePath and resolveLocalFileSystemURL not work.. :(

**Comment by darryncampbell** [comment]
Looks like you would need to fork & modify this plugin to get it to work successfully with WhatsApp, similar question on SO: https://stackoverflow.com/questions/47091040/unable-to-get-the-image-path-from-whatsapp-share-uri
