### ISSUE TITLE
Error log when tried to call the startActivity function, please find the error logs 

### ISSUE THREAD

**Issue by sriramede9** [darryncampbell/darryncampbell-cordova-plugin-intent#113]
[test_logs.txt](https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/files/5071670/test_logs.txt)

I have given options and called startActivity function and received the logs shown in the attachment, please help me with this error

here is the small snippet 

  this.webIntent.startActivity(options).then((success) => {
      this.intentResponse = "web intent success: " + JSON.stringify(success);
      console.log("web intent success:", success);
    }, (err) => {
      this.intentResponse = "web intent error: " + err;
      console.log("web intent error: ", err)
    });

**Comment by darryncampbell** [comment]
You may get a more verbose error message if you access the plugin directly rather than going through WebIntent, ` (<any>window).plugins.intentShim.startActivity(...)`

**Comment by sriramede9** [comment]
Many Thanks
