### ISSUE TITLE
Permission REQUEST_INSTALL_PACKAGES

### ISSUE THREAD

**Issue by EcoFreak** [darryncampbell/darryncampbell-cordova-plugin-intent#119]
Hello, Why is this plugin adding REQUEST_INSTALL_PACKAGES to the app's manifest file?

Thanks

**Comment by darryncampbell** [comment]
Hi, I had a use case to install an app by sending an intent so that required this permission. That is the only use case that needs it so feel free to fork and delete if this is giving your users concerns

**Comment by EcoFreak** [comment]
Oh ok, it's makes sense. Has anyone reported issues  raised by Google when submitting apps?

Thanks @darryncampbell

**Comment by darryncampbell** [comment]
No, nobody has reported any issues but the play store requirements are always subject to update. Are you seeing issues raised?

**Comment by EcoFreak** [comment]
@darryncampbell We had a couple of issues using cordova-plugin-app-update and I was updating one of our apps and saw the permissions list and was curious. If I have any problems in the future I'll let you know

**Comment by darryncampbell** [comment]
Ok, thanks for making me aware, I'll also keep an eye out for play store policy changes
