### ISSUE TITLE
Install the WebIntent plugin: 'ionic cordova plugin add com-darryncampbell-cordova-plugin-intent'

### ISSUE THREAD

**Issue by mobicraft-am** [darryncampbell/darryncampbell-cordova-plugin-intent#13]
When i want to use the Ionic Native WebIntent plugin, i always have this error Install the WebIntent plugin: 'ionic cordova plugin add com-darryncampbell-cordova-plugin-intent', but it's already installed like this :
$ ionic cordova plugin add com-darryncampbell-cordova-plugin-intent
$ npm install --save ionic-native/web-intent

@ionic/cli-plugin-cordova       : 1.6.2
@ionic/cli-plugin-ionic-angular : 1.4.1
@ionic/cli-utils                : 1.7.0
 ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    Node       : v6.6.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim    : 6.0.0 
    npm        : 5.3.0

**Comment by darryncampbell** [comment]
I believe this is related to the open issue at https://github.com/ionic-team/ionic-native/issues/1609, I did ask on that thread but don't think this is something I can solve in this plugin.

**Comment by pe1o2pl** [comment]
@mobicraft-am  this plugin is for android platform only

**Comment by pe1o2pl** [comment]
How to use it with Ionic/typescript:

1. Don't install ` @ionic-native/web-intent `- there is a bug so far
You need directly use intentShim() method.

2. Install the plugin: ionic cordova plugin add com-darryncampbell-cordova-plugin-intent

3. Add declaration: declare var intentShim: any;

4. Now you can call any method like this : 
```
(<any>window).plugins.intentShim.getIntent(
        function (intent) {
          alert("getIntent() :" + JSON.stringify(intent));
        },
        function () {
          alert('Error getting intent');
        });
```

**Comment by mobicraft-am** [comment]
Lol ? seriously ? ;-)))))

i have the problem on android dude …

**Comment by mobicraft-am** [comment]
OK i know that, but i have use the link on the ionic native page to declare the issue :

This plugin is still in beta stage and may not work as expected. Please submit any issues to the plugin repo <https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/issues>.

i need to contact the ionic team ;) 

thank u

**Comment by pe1o2pl** [comment]
Hi @darryncampbell 
> @pe1o2pl It looks like getUri() in the original plugin returned intent.getDataString(), https://github.com/darryncampbell/cordova-webintent/blob/master/src/android/WebIntent.java#L107. You can call getIntent() with my plugin to return a JSON representation of the calling intent; there is a 'data' extra in that returned intent which will be nearly the same as getUri() previously returned, https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/blob/master/src/android/IntentShim.java#L462. The difference is between getData() and getDataString(), let me know if getDataString() is required as well as getData().

Let me clear my scenario: I would like to launch the app when clicking on some url eg. `http://host_name/path` Then I need to parse the url in my app and call some activity depends on the url value.
So step 1: adding an intent filter to AndroidManifest.xml: 
```
 <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
              <data android:host="host_name" android:scheme="http" />
            </intent-filter>
```
ok, it works fine

Step2. Getting intent object inside my app
I have installed your plugin and added onIntend() listener:
```
plugins.intentShim.onIntent( intent => {
        alert("onIntent " + JSON.stringify(intent.data))
      })
```

ok, it works, `intend.data == http://host_name/path `
But the only first time` intend.data` is correct, Every next click on some other url eg. `http://host_name/path2` gives the same intent.data as previous ie `http://host_name/path`

So why i asked you about `getUrl()` method hoping for right value every time :)

**Comment by darryncampbell** [comment]
Can you call intentShim.getIntent() rather than rely on intentShim.onIntent()?  both methods should return intent.data.  Please see the ReadMe for example usage of getIntent() and it's also in the sample app: https://github.com/darryncampbell/plugin-intent-api-exerciser

**Comment by pe1o2pl** [comment]
Yep, I used your sample app api-exerciser (thanks), and got the same results as on my app. Both `onIntent()` and `getIntent()` works similar. Always get the same 'data' value regardless the url. I began to suppose that it is taken like from History and have started to research that topic.

**Comment by darryncampbell** [comment]
Closed with the resolution of https://github.com/ionic-team/ionic-native/issues/1609

**Comment by TheNaman47** [comment]
@pe1o2pl I am stuck while using this plugin of @darryncampbell . I have added the plugin and it is in config.xml. I tried with and without the node module but it keeps on saying that please install this module whenever I try to use it. Please help me with a solution.

**Comment by darryncampbell** [comment]
Please see https://github.com/Zebra/ZebraIonicDemo for an example project written in Ionic which accesses the plugin directly rather than using WebIntent
