### ISSUE TITLE
check if there is an app installed that can handle the given intent

### ISSUE THREAD

**Issue by DieOptimistin** [darryncampbell/darryncampbell-cordova-plugin-intent#17]
Currently the plugin is just firing an intent and don't cares if there is no app installed that can handle it. Nevertheless this is frequent error. Could you please extend it by this check?

```
 if (intent.resolveActivityInfo(mActivity.getPackageManager(), 0) != null) {
         mActivity.startActivity(intent);
} else {
        //throw error
 }
```

**Comment by darryncampbell** [comment]
Good idea 👍 updated as suggested.
