### ISSUE TITLE
installed this plugin and sayes not installed

### ISSUE THREAD

**Issue by ahmadrezakouhi** [darryncampbell/darryncampbell-cordova-plugin-intent#18]
Native: tried calling WebIntent.startActivity, but the WebIntent plugin is not installed

**Comment by darryncampbell** [comment]
Please see the ReadMe for an example usage: https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/blob/master/README.md Possibly also related to https://github.com/ionic-team/ionic-native/issues/1609

**Comment by darryncampbell** [comment]
Closed with the resolution of https://github.com/ionic-team/ionic-native/issues/1609
