### ISSUE TITLE
plugin no installed 

### ISSUE THREAD

**Issue by iknox27** [darryncampbell/darryncampbell-cordova-plugin-intent#2]
On ionic 2.x  its says plugin_not_installed, but i followed all the steps 

Native: tried calling WebIntent.ACTION_VIEW, but the WebIntent plugin is not installed.
Install the WebIntent plugin: 'ionic plugin add https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent.git'
main.js:46918 Native: tried calling WebIntent.startActivity, but the WebIntent plugin is not installed.

**Comment by darryncampbell** [comment]
Hi, I'm confused, the WebIntent plugin is here: https://www.npmjs.com/package/phonegap-webintent, this is NOT the WebIntent plugin.  Have you installed the plugin at https://www.npmjs.com/package/phonegap-webintent?

**Comment by iknox27** [comment]
did you have a simple example with ionic 2?

**Comment by darryncampbell** [comment]
No I'm afraid I do not, it is just a Cordova plugin so it should work in Ionic but it is not part of the ionic plugin market place and does not have any Angular wrappers as other plugins do at ngCordova.

**Comment by darryncampbell** [comment]
Can you please let me know what steps led to the original error?

**Comment by iknox27** [comment]
Hi darryn, thanks for your plugin, but i made my own plugin

**Comment by cimran** [comment]
@iknox27 would you mind sharing your plugin please? I am also stuck and working on Ionic 2 but not progressing anywhere. Would be of great help!
Thank you in advance :)
