### ISSUE TITLE
Unable to open local file with startActivity

### ISSUE THREAD

**Issue by goodevilgenius** [darryncampbell/darryncampbell-cordova-plugin-intent#21]
I have the path to a file from another plugin. I've tried the following to open the file in a default application:

```js
window.plugins.intentShim.startActivity(
{
    action: window.plugins.intentShim.ACTION_VIEW,
    url: '/path/to/file.jpg'
},
function() {console.log('success');},
function() {console.error('Failed')};
);
```

```js
window.plugins.intentShim.startActivity(
{
    action: window.plugins.intentShim.ACTION_VIEW,
    url: 'file:///path/to/file.jpg'
},
function() {console.log('success');},
function() {console.error('Failed')};
);
```

```js
window.plugins.intentShim.startActivity(
{
    action: window.plugins.intentShim.ACTION_VIEW,
    url: 'file://path/to/file.jpg'
},
function() {console.log('success');},
function() {console.error('Failed')};
);
```

All three of these failed.

**Comment by darryncampbell** [comment]
Hi, I had a similar example for launching an APK: https://github.com/darryncampbell/plugin-intent-api-exerciser/blob/master/www/js/index.js#L120.  If you use cordova.file.externalRootDirectory (or similar) so your code might look like:
var externalRoot = corodva.file.externalRootDirectory;
var picUri = externalRoot + 'file.jpg';

The Plugin provides a file provider for external-path which is Android's Environment.getExternalStorageDirectory(), so you will need to put your files somewhere there.
