### ISSUE TITLE
Calling finish for activity to close current app

### ISSUE THREAD

**Issue by fanfavorite** [darryncampbell/darryncampbell-cordova-plugin-intent#22]
I have an app that gets launched by another one. Is there a way to call finish() in this plugin to close the app that was opened and go back to the main app? I am thinking that the only existing way currently is to start the app using startActivityForResult and call sendResult. Is there a way without calling startActivityForResult or will that method even work? Let me know what I could do. Thanks!

**Comment by darryncampbell** [comment]
Hi, yes calling startActivityForResult & sendResult are currently the only way of calling finish().  You can call sendResult from your application regardless of how it was started which would call finish()... it's not really designed that way but it would work.

**Comment by darryncampbell** [comment]
Closing, assumed resolved
