### ISSUE TITLE
Can the intent be received on each page?

### ISSUE THREAD

**Issue by fanfavorite** [darryncampbell/darryncampbell-cordova-plugin-intent#23]
When my app is launched using an intent with extras, will window.plugins.intentShim.getIntent work on every page in my app or do I need to store the information in something like localStorage on the first page?

**Comment by nosTa1337** [comment]
I am working with ionic and have created a provider for this where I make a subscribe to the intentshim and working with a replaysubject to be able to listen for changes on every page I like.

calling this in my provider constructor:
````
  public barcode$: ReplaySubject<string> = new ReplaySubject<string>();
  private intentShim: any;

  private registerDataWedgeListener()
  {
    if (this.platform.is('cordova') && this.settings.isDataWedge)
    {
      (<any>window).plugins.intentShim.registerBroadcastReceiver({
        filterActions: ['de.all4cloud.scan4cloud.ACTION'],
        filterCategories: ['com.android.intent.category.DEFAULT']
      }, (intent) =>
        {
          console.log(intent.extras["com.symbol.datawedge.data_string"]);
          this.barcode$.next(intent.extras["com.symbol.datawedge.data_string"]);
        });
    }
  }
````

than on my subpage I need the result I am doing it the following way:
````
    private initScanProvider()
    {
        if (this.isDataWedge)
        {
            this.scanProvider.barcode$
                .takeUntil(this.componentDestroyed$)
                .subscribe((data) =>
                {
                    this.scan(data);
                })
        }
    }
````

**Comment by darryncampbell** [comment]
Hi, sorry I missed this... window.plugins.intentShim.getIntent calls https://developer.android.com/reference/android/app/Activity.html#getIntent() under the covers so you should be able to call getIntent() wherever your application needs it as long as your whole app runs in the same activity.  If your app spans multiple activities then something like @nosTa1337 suggested will be required.
