### ISSUE TITLE
How to listening android.intent.action.PACKAGE_ADDED？

### ISSUE THREAD

**Issue by CjoyHome** [darryncampbell/darryncampbell-cordova-plugin-intent#24]
Is it possible to receive the broadcast from android.intent.action.PACKAGE_ADDED？

**Comment by darryncampbell** [comment]
Hmmm possibly not.  The plugin is only able to add a filter action (https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/blob/master/src/android/IntentShim.java#L204) but most sources say to add a data filter also e.g. https://stackoverflow.com/questions/40965771/intent-filter-for-package-added-for-a-specific-package.  I have never tried it myself, I would be interested in the results.

**Comment by darryncampbell** [comment]
I have added support for data schemes in version 0.0.16.  You should now be able to register for PACKAGE_ADDED as follows:
```javascript
    window.plugins.intentShim.registerBroadcastReceiver({
        filterActions: [
            'android.intent.action.PACKAGE_ADDED'
            ],
        filterDataSchemes: [
	    'package'
	    ]
        },
        function(intent) {
            //  Broadcast received
            console.log('Package Installed Name: ' + JSON.stringify(intent.data));
            console.log('Package Installed Extras: ' + JSON.stringify(intent.extras));
        }
    );
```

**Comment by CjoyHome** [comment]
Thank you for your help.
I tried to use it in ionic3.
First,  
cordova plugin add com-darryncampbell-cordova-plugin-intent
My Cordova is 8.0.0.
Then, ts:
(<any>window).plugins.intentShim.registerBroadcastReceiver({
        filterActions: [
          'android.intent.action.PACKAGE_ADDED'
        ],
        filterDataSchemes: [
          'package'
        ]
      },
      function(intent) {
        //  Broadcast received
        console.log('Package Installed Name: ' + JSON.stringify(intent.data));
        console.log('Package Installed Extras: ' + JSON.stringify(intent.extras));
      }
    );
When I registered the Broadcast to download, it didn't respond.

**Comment by CjoyHome** [comment]
After the installation is successful, it didn't respond.

**Comment by darryncampbell** [comment]
Your application is in the foreground during installation?  The plugin will only register for broadcasts when it is in the foreground (and unregister when moved to the background).  Also, you might want to just double check you have version 0.0.16 installed with `cordova plugin ls`

**Comment by CjoyHome** [comment]
When I install the program, my app is in the background，
com-darryncampbell-cordova-plugin-intent 0.0.16 "Intent Shim"

**Comment by darryncampbell** [comment]
Ah, you will only receive the broadcast if your application is in the foreground with this plugin.

**Comment by CjoyHome** [comment]
Installing an application will definitely bring the application background.How to solve this problem?Android native I don 't understand

**Comment by darryncampbell** [comment]
Actually, looking at the code at https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/blob/master/src/android/IntentShim.java I don't see any logic to unregister the plugin when the application comes to the foreground so maybe it would work.  I tested with https://github.com/darryncampbell/plugin-intent-api-exerciser (which does unregister the receiver in onPause() ) and installed the application using adb.

**Comment by CjoyHome** [comment]
Should I use https://github.com/darryncampbell/plugin-intent-api-exerciser ？

**Comment by darryncampbell** [comment]
I developed https://github.com/darryncampbell/plugin-intent-api-exerciser alongside the plugin to test the plugin's functionality as it was developed so you could use it as a reference application or a source of sample code but I wouldn't advocate using it in production.  Hope that helps.

**Comment by CjoyHome** [comment]
I still can't solve this problem,I think it might not be a broadcast cancellation,But when running in the background, JS did not receive it.
I tried to use the BatteryStatus ionic nactive Cordova,I found that I could receive when I was running at the foreground, and I didn't receive in the background, but I still kept the receive  when you put it again.

**Comment by CjoyHome** [comment]
Recommend to see http://www.it1352.com/550915.html

**Comment by darryncampbell** [comment]
That link is talking about push messaging and an issue with the GCM (now FCM) plugin, that is not general background broadcasts.  Perhaps you need to develop your own plugin if this plugin does not meet your needs, feel free to fork this project as it is released under MIT.

**Comment by CjoyHome** [comment]
I found a plugin that can be executed in the background,It‘s Background Mode (https://ionicframework.com/docs/native/background-mode/)
So can you listen to the android.intent.action.PACKAGE_ADDED through your plugin?

**Comment by darryncampbell** [comment]
That plugin is using a Foreground service so I don't think it would be compatible, my plugin will register a broadcast receiver on the main activity.  I suggest registering for PACKAGE_ADDED using the code I listed higher up in this thread and ensuring you do not unregister the broadcast receiver on pause.
