### ISSUE TITLE
ionic 3 intent

### ISSUE THREAD

**Issue by vladimircojuhari** [darryncampbell/darryncampbell-cordova-plugin-intent#26]
hi. i need to send PDF to my app. can i do it with this plugin on ionic 3 and get it to send on server? i tried intent plugin on ionic 1 and it was quite easy to do. help pls and can you write a small guide for this.

**Comment by darryncampbell** [comment]
Hi, I'm not 100% sure what you are trying to do but if it is working in Ionic 1 it should work with Ionic 2 or 3 with TypeScript.  Install the plugin as you would have done for Ionic 1 then access the plugin with (<any>window).plugins.intentShim.blah.  There is a sample app that uses the plugin here: https://github.com/darryncampbell/DataWedgeIonic2/blob/master/src/pages/home/home.ts.  It does not do what you want but it shows the Plugin being used with Ionic 2 (3 will have the same syntax)
