### ISSUE TITLE
AndroidLaunchMode singleTask cannot read intents

### ISSUE THREAD

**Issue by madskonradsen** [darryncampbell/darryncampbell-cordova-plugin-intent#27]
Hey, I'm using the intent-exerciser to test out the plugin in my own app. When I launch the intent-exerciser with singleTop launchmode, the intent is correctly read by the exerciser-app, but as soon as I switch it to singleTask, the intent can't be read anymore(the intent action is just shown as the default "android.intent.action.MAIN"). Have you encountered something similar?

**Comment by darryncampbell** [comment]
Hi, yes, I have come across something similar.  I put a brief note in the ReadMe file for this plugin but I found the following blog useful: https://www.mobomo.com/2011/06/android-understanding-activity-launchmode/

**Comment by madskonradsen** [comment]
Nice, thanks, it was a good read. I'm not sure of whether the bug is in the plugin, the exerciser-apps configuration, or in Android :-/ I guess it must be the configuration of the exerciser-app since thats the only things that I change... Oh well... I guess I have to play a bit more with the settings...
