### ISSUE TITLE
Ionic Focussed Input Problem With Scanner And Datawedge

### ISSUE THREAD

**Issue by Gundelino85** [darryncampbell/darryncampbell-cordova-plugin-intent#28]
Hi,

i have a problem with focussed input. I don't want the content of the scanned QR-code put directly into the focussed input. I hope i can prevent this in the config of registerBroadcastReceiver...

Thx and best regards! :)

**Comment by darryncampbell** [comment]
Hi, this is for DataWedge on Zebra devices presumably?  I wrote a tutorial / example app on this very subject so please take a look: http://www.darryncampbell.co.uk/2017/12/14/ionic-2-support-on-zebra-enterprise-devices/  Hope that helps.
