### ISSUE TITLE
Send result back to the caller

### ISSUE THREAD

**Issue by OtaconRex** [darryncampbell/darryncampbell-cordova-plugin-intent#3]
Hi, i am working on ionic v1 app and i installed this plugin to let another android app call mine, that part is fine, but, i don't see how my app can send a result to the caller, this plugin can do that?

another thing can i fork this plugin?, if not, can i work for it?

**Comment by OtaconRex** [comment]
Hi again, i think i solve my own problem with sending back the result, what i do y mode a little your code to do what a wanted, first i change your `IntentShim` java class in the `execute` function and add this in after `else if (action.equals("getIntent"))`

`
else if(action.equals("sendResult"))
{
	//instaciate the result intent
	Intent result = new Intent("com.example.RESULT_ACTION", Uri.parse("content://result_uri"));

	//recover the result you want to send
	JSONObject json = args.getJSONObject(0);
	JSONObject extras = (json.has("extras"))?json.getJSONObject("extras"):null;

	// Populate the extras if any exist
	if (extras != null) {
		JSONArray extraNames = extras.names();
		for (int i = 0; i < extraNames.length(); i++) {
			String key = extraNames.getString(i);
			String value = extras.getString(key);
			result.putExtra(key, value);
		}
	}

	//set result
	cordova.getActivity().setResult(Activity.RESULT_OK, result);

	//finish the activity
	cordova.getActivity().finish();

	callbackContext.sendPluginResult(new PluginResult(PluginResult.Status.OK));
	return true;
}
`

then i change the `IntentShim` javascript to add this new function

`IntentShim.prototype.sendResult = function(params, callback){
    argscheck.checkArgs('of', 'IntentShim.sendResult', arguments);
    exec(callback,null,"IntentShim","sendResult",[params]);
}`

finally it is only compile everything and tested in my app and work very well and do what i need to do, but i will test this in other device and see if it is working always.

i hope you take this and add it to the master, and developer a little more than i

thank you in advance for everything and for creating this plugin

PS: my question is still going can i fork this plugin?, if not, can i work for it?

have a nice day

**Comment by darryncampbell** [comment]
Hi, thanks for this, I'll add it to master but let me take a better look at it first.  I'm currently travelling so might take me a couple of weeks.  Yes, feel free to fork the plugin, it is released under MIT.

**Comment by darryncampbell** [comment]
Hi, this has now been added with the following commit to version 0.0.8: https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/commit/4a8f7fe37f4da76a0cf64bc2f316b1004ba90352
