### ISSUE TITLE
How to share image to other apps

### ISSUE THREAD

**Issue by mineral99** [darryncampbell/darryncampbell-cordova-plugin-intent#30]
Hello,

Please show me some example coding for action SEND, and SEND_TO.
This is my code that not working

window.plugins.intentShim.startActivityForResult(
{
action: window.plugins.intentShim.ACTION_SEND,
requestCode: 1,
extras: {
"android.intent.extra.STREAM": "file:///storage/emulated/0/Pictures/test_album/2018-0-23-4.png"
}
},
function (intent) {
if (intent.extras.requestCode == 1 && intent.extras.resultCode == window.plugins.intentShim.RESULT_OK) {
alert('Picked contact: ' + intent.data);
document.getElementById('startActivityResultData').innerHTML = "Picked Contact: " + intent.data;
}
else {
document.getElementById('startActivityResultData').innerHTML = "Picked Contacted Canceled";
}
},
function (e) {
document.getElementById('startActivityResultData').innerHTML = "StartActivityForResult failure" + e;
}
);

Thank you

**Comment by darryncampbell** [comment]
There was a bug which prevented this from being possible.  I have updated the sample application also
