### ISSUE TITLE
Cannot add the latest release

### ISSUE THREAD

**Issue by hoboman313** [darryncampbell/darryncampbell-cordova-plugin-intent#32]
_cordova plugin add com-darryncampbell-cordova-plugin-intent@0.0.18 --nofetch_

Fetching plugin "com-darryncampbell-cordova-plugin-intent@0.0.18" via npm
Error: Invalid attribute name
Line: 1
Column: 83
Char: /

**Comment by darryncampbell** [comment]
Wow that was a dumb mistake :/ fixed in 0.0.19.  Thanks for raising.
