### ISSUE TITLE
Set intent package

### ISSUE THREAD

**Issue by gnujeremie** [darryncampbell/darryncampbell-cordova-plugin-intent#33]
Is there a way to set the package to which I need to send an intend ?
For something like that : 
```
Android.Content.Intent intent = new Android.Content.Intent("fr.myvendor.intent.action.stop.barcode.service");
intent.SetPackage("fr.myvendor.service.cfive");
```

**Comment by darryncampbell** [comment]
Hi, right now I'm afraid there is no way to do this.  It wouldn't be difficult to add so I'll label it as enhancement and maybe add it in the future (but I can't comment on any timescales).  Thanks.

**Comment by darryncampbell** [comment]
Added to version 0.0.20

**Comment by gnujeremie** [comment]
Awesome, I'll check this out !

**Comment by nazmicancalik** [comment]
@darryncampbell Hi, I was trying to target a specific package by adding the package field as follows but it doesn't seem to work. 

`
const intentOptions = {
                action: window.plugins.intentShim.ACTION_VIEW,
                package: "com.test.adfs.getintenttest"
                extras: {
                    itemName: $scope.itemName,
                    itemImg: 'https://sc01.alicdn.com/a.img'
                }
            };

window.plugins.intentShim.startActivityForResult(
                    intentOptions,
                    function(json){
                        alert("success");
                        alert(JSON.stringify(json,null,2));
                    },
                    function(err){
                        alert("er");
                        alert(JSON.stringify(err,null,2));
                    }
                );
`
Can you take a look at this, thanks.

**Comment by darryncampbell** [comment]
@nazmicancalik You are missing a comma after your package name, could that be the issue?

**Comment by nazmicancalik** [comment]
@darryncampbell I probably deleted the comma when pasting here, I have doublechecked even though but it still doesn't work. 

```
const intentOptions = {
              
                package: "com.test.abc.getintenttest",
                extras: {
                    itemName: $scope.itemName,
                    itemImg: 'https://sc01.alicdn.com/kf/abc/150ml-225mabcczer.jpg_50x50.jpg'
                }
            };

            
            $scope.arButtonClick = function () {
                alert('Sending the intent');
                window.plugins.intentShim.startActivityForResult(
                    intentOptions,
                    function(json){
                        alert("success");
                        alert(JSON.stringify(json,null,2));
                    },
                    function(err){
                        alert("er");
                        alert(JSON.stringify(err,null,2));
                    }
                );
            };
```

**Comment by darryncampbell** [comment]
I have a test app that I use for this plugin, https://github.com/darryncampbell/plugin-intent-api-exerciser.
If I execute the following then the package seems to work (of course, the contacts package name needs to match the actual contacts app on your phone):
window.plugins.intentShim.startActivityForResult(
            {
                action: window.plugins.intentShim.ACTION_PICK,
                url: "content://com.android.contacts/contacts",
				package: "com.android.contacts",
                requestCode: 1
            },
            function(intent)
            {
                if (intent.extras.requestCode == 1 && intent.extras.resultCode == window.plugins.intentShim.RESULT_OK)
                {
                    console.log('Picked contact: ' + intent.data);
                    document.getElementById('startActivityResultData').innerHTML = "Picked Contact: " + intent.data;
                }
                else
                {
                    document.getElementById('startActivityResultData').innerHTML = "Picked Contacted Canceled";
                }
            },
            function()
            {
                document.getElementById('startActivityResultData').innerHTML = "StartActivityForResult failure";
            }
        );
Can you reproduce the issue with the test app?

**Comment by nazmicancalik** [comment]
@darryncampbell 
If I use it like the following

```
window.plugins.intentShim.startActivityForResult(
            {
                package: "com.samsung.android.contacts",
                requestCode: 1
            },
            function(intent)
            {
                if (intent.extras.requestCode == 1 && intent.extras.resultCode == window.plugins.intentShim.RESULT_OK)
                {
                    console.log('Picked contact: ' + intent.data);
                    document.getElementById('startActivityResultData').innerHTML = "Picked Contact: " + intent.data;
                }
                else
                {
                    document.getElementById('startActivityResultData').innerHTML = "Picked Contacted Canceled";
                }
            },
            function()
            {
                document.getElementById('startActivityResultData').innerHTML = "StartActivityForResult failure";
            }
        );
```

it works, it opens the contacts

But if I also add action (Action Pick) then it doesn't work.
