### ISSUE TITLE
Open external application

### ISSUE THREAD

**Issue by petreionescu** [darryncampbell/darryncampbell-cordova-plugin-intent#34]
Hello and thanks for the plugin.
Is it posible to launch externall application after verifying if it is installed using startActivity method?

**Comment by darryncampbell** [comment]
Hi, if you call startActivity then internally the plugin will call resolveActivityInfo https://developer.android.com/reference/android/content/Intent.html#resolveActivityInfo(android.content.pm.PackageManager, int) , the line of code is here: https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/blob/master/src/android/IntentShim.java#L370 .  You get an error back it looks like if the app is not installed.

Are you asking for a separate method to expose resolveActivity so you can determine yourself if the intent will resolve or is the current functionality enough?

**Comment by petreionescu** [comment]
hi, i wanted to be able to launch specific external applications like CamScanner using startActivity

**Comment by darryncampbell** [comment]
Right now this plugin only supports sending implicit intents so you could only do this if CamScanner is listening for some specific Intent Action.
