### ISSUE TITLE
startService(intent)

### ISSUE THREAD

**Issue by gnujeremie** [darryncampbell/darryncampbell-cordova-plugin-intent#36]
Hi,

I've been given this code example :

```
Android.Content.Intent intent = new Android.Content.Intent("fr.namespace.intent.action.stop.barcode.service");
intent.SetPackage("fr.namespace.service.device");
startService(intent)
```

but i'm not sure the ```startService(intent)``` is possible with your package. Did I miss something ?

Thanks

**Comment by darryncampbell** [comment]
No, sorry it doesn't do startService... just startActivity and sendBroadcast.  No particular reason, just the original plugins I based this on didn't have the feature and you are the first person to ask.  I'll mark this as an enhancement.

**Comment by gnujeremie** [comment]
Cool, thanks for the reply :)

**Comment by darryncampbell** [comment]
I was doing some refactoring in the latest version so added startService also.
You should be able to do something like the following with the latest version:
window.plugins.intentShim.startService(
            {
                action: "fr.namespace.intent.action.stop.barcode.service",
		package: "fr.namespace.service.device"
            },
            function()
            {
		//  Success
            },
            function()
            {
		//  Error
            }
        );
In my testing though, I specified the entire component: https://github.com/darryncampbell/plugin-intent-api-exerciser/blob/master/www/js/index.js#L264
