### ISSUE TITLE
Can no longer build Cordova with this plugin

### ISSUE THREAD

**Issue by RittenInc** [darryncampbell/darryncampbell-cordova-plugin-intent#38]
Hi,

I have been using this plugin, and it has been working great! However recent updates seem to have broken the plugin.

Create new project, add this and only this plugin. 

cordova plugin add com-darryncampbell-cordova-plugin-intent
cordova platform add android
cordova run android

`:app:processDebugResourcesC:\Users\me\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0-alpha1.aar\1cef07b5640ca04267708cb0ed9b2629\res\values\values.xml:20:5-70: AAPT: error: re
source android:attr/fontVariationSettings not found.

C:\Users\me\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0-alpha1.aar\1cef07b5640ca04267708cb0ed9b2629\res\values\values.xml:20:5-70: AAPT: error: resource android:attr/ttcInd
ex not found.

C:\Projects\POS\cordova\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:86: error: resource android:attr/fontVariationSettings n
ot found.
C:\Projects\POS\cordova\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:86: error: resource android:attr/ttcIndex not found.
error: failed linking references.

 FAILED
`

Cordova Version: 8.0.0
Android Version: Everything above 6.2.3 (it does work for this version)

It does work for 6.2.3, however i built a lot of applications on android 7.0.0 that are now failing. I would prefer to not have to regress my applications because I require this fantastic plugin. 

Any help would be greatly appreciated.

**Comment by darryncampbell** [comment]
Strange, I was working on a Cordova application earlier today and it was working for me (Cordova 8.0.0 with Android platform 7.0.0).  Can you please try cleaning and rebuilding?  Looks like the resources are throwing some errors.  Or maybe uninstalling and reinstalling the plugin?

**Comment by darryncampbell** [comment]
Here is the project I was working on today that is "working for me" https://github.com/darryncampbell/DataWedgeCordova/tree/DW6.5Improvements (note the branch)

**Comment by kevinnba13** [comment]
@RittenInc @darryncampbell 

I have the same problem

(Cordova 8.0.0 with Android platform 7.0.0).

**Comment by darryncampbell** [comment]
Thank you!  I do not have version 28 of the support library installed so that probably explains why I did not see this issue.  I have fixed it in the latest version (finally bumped to 1.0.0).

**Comment by viking2917** [comment]
I wonder if it's possible to use an earlier support-v4 than 27? It breaks compatibility with other heavily used plugins such as the Facebook plugin (esp: v 1.7.4 heavily used, see https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/606 and https://github.com/jeduan/cordova-plugin-facebook4/issues/507) . 

E.g. I see:

```
ionic start intentCompileTest blank --type ionic1
cd intentCompileTest/
ionic cordova build android  (this works)
ionic cordova plugin add cordova-plugin-facebook4@1.7.4 --save --variable APP_ID="<>" --variable APP_NAME="<>"
ionic cordova build android  (this works)
cordova plugin add com-darryncampbell-cordova-plugin-intent
ionic cordova build android  (this fails)
```

However if I change your plugin xml to:

`	<framework src="com.android.support:support-v4:24.1.1+" />
`

things compile OK.

**Comment by darryncampbell** [comment]
Hi @viking2917 apologies for the delayed reply but I have been away.  I'm happy to change the version to 4:24.1.1+ as long as that would work for all.  Sorry if this is a silly question, but would 24.1.1+ pull in version 28.0.0 if that was installed on the development machine?  Just want to make sure the original issue is also solved.

**Comment by viking2917** [comment]
Hi @darryncampbell thanks and no worries. Thanks for making this plugin!

I am not enough of an Android expert to really know for sure, but I suspect the answer is no, 24.1.1+ only gets 24.1.x. There may not be a good way to do what I am asking for, and I realize it's an older version. The only reason I raised an issue is that it does conflict with some heavily used (but also older) plugins like Facebook one I mentioned. 

In any case I've forked this repo and set the build number as I need it, so I'm set for the moment, it may be best to just leave as is....

(in case useful to anyone my fork is https://github.com/viking2917/darryncampbell-cordova-plugin-intent - it also includes a change to add the "Share" intent to the manifest. My use case is making my app show up in the "share" menu for text items, for example text selected in the Kindle app, which can be shared to my bookclub app Bookship.

**Comment by darryncampbell** [comment]
OK, so one option would be to change the version to 24.1.1 (without the +) however I would have concerns doing that in case it breaks compatibility with some other plugins (this particular version has used 27 for a long time apart from the accidental change which started this thread).

I propose to:
* **not** change this plugin to use version 24.1.1, the version of the support library will remain at 27.1.0
* Anybody wishing to use this plugin with the facebook plugin can use the fork you provided above
* If additional plugins are identified that require support library 24 we can revisit the issue.

I will close this issue unless there are further concerns.  Thanks.

**Comment by davidquon** [comment]
I'm having this problem as well where I need `<framework src="com.android.support:support-v4:24.1.1+" />` due to being tied to older versions of Cordova and Android platform.  Using Cordova only for this problematic project without Ionic.

```
Node version: v7.1.0
Cordova version: 6.5.0
    <engine name="android" spec="~6.1.2" />
    <plugin name="com-darryncampbell-cordova-plugin-intent" spec="https://github.com/iParqDevelopers/darryncampbell-cordova-plugin-intent.git#ritd" />
```

Also ended up fixing this by forking https://github.com/iParqDevelopers/darryncampbell-cordova-plugin-intent/tree/ritd and just changing the reference in `plugin.xml` to `com.android.support:support-v4:24.1.1+`.
