### ISSUE TITLE
Intent to install APK

### ISSUE THREAD

**Issue by mamcgree** [darryncampbell/darryncampbell-cordova-plugin-intent#4]
Greetings..

Prior to nougat I was able to install apk with your plugin.
options = {
      action: window.plugins.intentShim.ACTION_VIEW,
      url: 'file:///storage/.....apk',
      type: 'application/vnd.android.package-archive'
    }
Nougat now requires a fileProvider and use the action ACTION_INSTALL_PACKAGE for the intent.
I am not skilled enough to modify your plugin.
Please advise..
Thank you in advance

**Comment by darryncampbell** [comment]
Hi, I have added this to version 0.0.8.  There might have been a better way to do it but it is working at least (tested on N).  See this example: https://github.com/darryncampbell/plugin-intent-api-exerciser/blob/master/www/js/index.js#L112
