### ISSUE TITLE
is it possible to uninstall app with intent ?

### ISSUE THREAD

**Issue by shomid** [darryncampbell/darryncampbell-cordova-plugin-intent#40]
how to uninstall app with intent ?
how to implement following code ?
`Uri packageUri = Uri.parse("package:org.klnusbaum.test");`
 `Intent uninstallIntent = new Intent(Intent.ACTION_UNINSTALL_PACKAGE, packageUri);`
`startActivity(uninstallIntent);`

**Comment by darryncampbell** [comment]
Hi, can you try:
window.plugins.intentShim.startActivity(
        {
            action: window.plugins.intentShim.ACTION_UNINSTALL_PACKAGE,
            url: 'package:org.klnusbaum.test'
        },
        function() {},
        function(info)
        {
            //  Check log, enable unknown sources installation and grant read access to storage
            alert('Failed to install application: ' + info)
        }
    );
Note: This is untested.

**Comment by darryncampbell** [comment]
Finally got around to testing this syntax myself it it works.  Closing this issue.

**Comment by sachi097** [comment]
Trying with one of the App with package : 'com.img.events' in my device.
Above code executes success callback but it is not leading to App uninstall wizard.

Any idea how to achieve this.

**Comment by darryncampbell** [comment]
You probably need to add a manifest permission, see https://stackoverflow.com/questions/58614644/android-9-intent-action-uninstall-package-not-working

**Comment by sachi097** [comment]
It worked like a charm after adding this to my Ionic App's config.xml
`<config-file target="AndroidManifest.xml" parent="/manifest">
        <uses-permission android:name="android.permission.INTERNET"/>
 </config-file>`
