### ISSUE TITLE
extras type as boolean or int, currently only string type is supported

### ISSUE THREAD

**Issue by mcelotti** [darryncampbell/darryncampbell-cordova-plugin-intent#41]
Hi,
the current extrasMap handles only string extras therefore options like this:
```
options = {
    ...
    extras: {
        requestToken: true,
        ...
    }
},
```
... will be sent as string.

**Comment by darryncampbell** [comment]
**Agreed this could be improved so labelling as an enhancement.**  Note that currently if you specify a JSON object for the request token this will be converted to a bundle and any integers specified in the JSON object are converted correctly within that bundle.

**Comment by mcelotti** [comment]
Thank you Darryn, I noticed that "toBundle" method does not handle Boolean, I could use the bundle if you add the boolean section.

**Comment by darryncampbell** [comment]
I had a meeting cancelled so I implemented the Boolean in the toBundle method (just an oversight that it wasn't there).  You should be able to now specify booleans as part of bundle extras options

**Comment by darryncampbell** [comment]
Closing as resolved by https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/pull/43
