### ISSUE TITLE
Is it posibble to receive intent data when the app is closed?

### ISSUE THREAD

**Issue by AlexRojasEmpowerlabs** [darryncampbell/darryncampbell-cordova-plugin-intent#48]
On Android 6.0.1. I have the plugin working perfectly when the cordova app is open, but when I close the cordova app and go to other app (like Pinterest, Chrome, Facebook) and try to send data to my app again, the **onIntent event** is not triggered. 

Any idea about how to solve this?

Thanks for this amazing plugin.

**Comment by darryncampbell** [comment]
Hi thanks, onIntent maps to Android's onNewIntent https://developer.android.com/reference/android/app/Activity.html#onNewIntent(android.content.Intent) which requires some combination of singleTop or the single top flag.  You could use getIntent exposed by this plugin to return the intent that started the activity, this maps to https://developer.android.com/reference/android/app/Activity.html#getIntent()

**Comment by AlexRojasEmpowerlabs** [comment]
Good idea. I'll try to do it.Thanks
