### ISSUE TITLE
Ionic does not build with this plugin

### ISSUE THREAD

**Issue by apo-j** [darryncampbell/darryncampbell-cordova-plugin-intent#49]
Hello, I'm trying to install this plugin into my ionic project with the following versions: 
- ionic version: 3.20.0
- cordova version: 8.0.0
- darryncampbell-cordova-plugin-intent version: 1.0.2

But after installation, when I run: **ionic cordova build android**
I got this error:

`FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
>
:app:generateDebugSources UP-TO-DATE
:app:javaPreCompileDebug FAILED
26 actionable tasks: 1 executed, 25 up-to-date
Could not find common.jar (android.arch.core:common:1.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/core/common/1.1.0/common-1.1.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
(node:18440) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find common.jar (android.arch.core:common:1.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/core/common/1.1.0/common-1.1.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
    at ChildProcess.whenDone (D:\Soyou\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:18440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Can you know why it's doing this ?

**Comment by darryncampbell** [comment]
I just tried building an app from scratch and it seems to work
- Cordova version 8.0.0
- Ionic version 3.2.0
- intent version 3.2.0
It pulls in cordova-android 7.0.0 and targets api 26.  Do you have your android build environment up to date?
We had a similar issue before (https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/issues/38), in that instance the support framework version was causing conflict with other plugins so possibly there is an undesirable interaction with some other plugin in your application?

**Comment by apo-j** [comment]
@darryncampbell What do you mean by **intent version 3.2.0** (darryncampbell-cordova-plugin-intent or @ionic-native/web-intent) ? for me, I have

- darryncampbell-cordova-plugin-intent: 1.0.2
- @ionic-native/web-intent: 4.7.0

**Comment by darryncampbell** [comment]
Darn it, sorry, that was a typo.  I meant it was version 1.0.2 of this intent, same as you.  Also with ionic-native/web-intent installed the app still builds and launcher.  Very strange.

**Comment by darryncampbell** [comment]
Closing the issue, assumed resolved.

**Comment by adityamaple1989** [comment]
cordova plugin add https://github.com/napolitano/cordova-plugin-intent.
After installation of above plugin,I am unable to build the apk.Please respond and please give any suggestion.
Its throwing an error like this
 no such file or directory, open './platforms/android/gradle.properties'

**Comment by darryncampbell** [comment]
@adityamaple1989 This is not the same plugin and that plugin by napolitano is marked as deprecated.

**Comment by adityamaple1989** [comment]
@darryncampbell  ok thanks for your reply and 
ionic plugin add https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent --save
the above plugins also I am unable to build the apk in ionic framework

**Comment by adityamaple1989** [comment]
@darryncampbell please suggest me,I need to use this plugin  receiving data from other apps

**Comment by darryncampbell** [comment]
@adityamaple1989 I suggest you take a look at an example project that uses this plugin for Ionic, https://github.com/Zebra/ZebraIonicDemo

**Comment by adityamaple1989** [comment]
Ok thank you,i will check.

**Comment by adityamaple1989** [comment]
@darryncampbell  what is the use of this url : https://github.com/Zebra/ZebraIonicDemo,I think it is not a plugin.By using this url we can receive data or any file from other apps?can you please tell me
