### ISSUE TITLE
Update to 0.0.8 breaks build

### ISSUE THREAD

**Issue by niteshgrg** [darryncampbell/darryncampbell-cordova-plugin-intent#5]
After updating it gives error as it doesnt seems to be creating file_paths file. As in new update config-file will only change file if it already exists. It ignores the changes if the file is not present.
 
```
Total time: 6.05 secs
Error: /parking-genius/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/parking-genius/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml:71:35-50: AAPT: No resource found that matches the given name (at 'resource' with value '@xml/file_paths').

/parking-genius/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml:69: error: Error: No resource found that matches the given name (at 'resource' with value '@xml/file_paths').



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by darryncampbell** [comment]
Thanks, I'll look into how to create a new file if it doesn't exist. In the mean time please either use 0.0.7 or create the file manually, the contents are defined in plugin.xml

**Comment by darryncampbell** [comment]
This should now be fixed under https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/commit/e74bac092fc23f04a7b65174613ee948d69c2fe6.  Released as 0.0.9.  Thanks.

**Comment by niteshgrg** [comment]
Thanks. Also just a question onIntent gets only fired up if app is running. Like if app was running and then i open some activity with intent from some other app it gets fired up. Else cordova splash screen and natural cycle seems to ignore first intent that called the app so it doesnt get fired.

**Comment by darryncampbell** [comment]
onIntent just maps to Android's Activity.OnNewIntent and I believe that is how it is supposed to work, from the documentation: "This is called for activities that set launchMode to "singleTop" in their package, or if a client used the FLAG_ACTIVITY_SINGLE_TOP flag when calling startActivity(Intent). In either case, when the activity is re-launched while at the top of the activity stack instead of a new instance of the activity being started, onNewIntent() will be called on the existing instance with the Intent that was used to re-launch it."

I believe Cordova will set the activity to singleTop by default.

**Comment by niteshgrg** [comment]
Ok this will only get invoked if pre launched activity is launched again. Can i recieve intent is activity is launched for first time too ?

**Comment by darryncampbell** [comment]
You can get the intent which initially launched the activity with getIntent().  Please see https://github.com/darryncampbell/plugin-intent-api-exerciser/blob/master/www/js/index.js#L207

**Comment by niteshgrg** [comment]
Thanks. Will try this
