### ISSUE TITLE
Build error - Cannot find Symbol variable N

### ISSUE THREAD

**Issue by pietervw** [darryncampbell/darryncampbell-cordova-plugin-intent#55]
Hi,

I'm having build errors when creating a blank Cordova app with and only include the plugin.

```
IntentShim.java:359
if(Build.Version.SDK_INT >= Build.VERSION_CODES.N && uniAriString.startsWith("file://"))
symbol: variable N
```

Cordova version 6.31.

Any advice?

**Comment by darryncampbell** [comment]
Hmmm... maybe related to the change I made this morning - I suggest using version 1.0.4 of the plugin (current version is 1.1.0)

**Comment by darryncampbell** [comment]
Actually, thinking about it properly, it sounds like you need to have a more recent version of the Android SDK since N is defined at API level 24, https://cordova.apache.org/docs/en/latest/guide/platforms/android/

**Comment by darryncampbell** [comment]
Presumed resolved
