### ISSUE TITLE
How to call intent for ACTION_VIDEO_CAPTURE

### ISSUE THREAD

**Issue by cfguimaraes** [darryncampbell/darryncampbell-cordova-plugin-intent#56]
First of all, sorry for my poor English.

I'm trying to call startActivityForResult to capture vídeo, without success :(

Google a lot of hours, read source code and can't figure how to use this plugin to call Photo & Video register Action.

**Comment by darryncampbell** [comment]
window.plugins.intentShim.startActivityForResult(
            {
                action: "android.media.action.VIDEO_CAPTURE",
                requestCode: 1
            },
            function(intent)
            {
                if (intent.extras.requestCode == 1 && intent.extras.resultCode == window.plugins.intentShim.RESULT_OK)
                {
                    console.log('Recorded video: ' + intent.data);
                }
                else
                {
					console.log('Record video canceled');
                }
            },
            function()
            {
				console.log('Record video failure');
            }
        );

You would then need to handle intent.data in the same way as https://developer.android.com/training/camera/videobasics.  I'm not entirely sure how to do that in Cordova
