### ISSUE TITLE
package com.darryncampbell.cordova.plugin.intent.api.exerciser does not exist

### ISSUE THREAD

**Issue by mamcgree** [darryncampbell/darryncampbell-cordova-plugin-intent#6]
Hi Darryn..
Thanks for changing #4 so quickly, but now I get the following message when compiling.
package com.darryncampbell.cordova.plugin.intent.api.exerciser does not exist

Thanks..

**Comment by darryncampbell** [comment]
Strange, it definitely exists up at https://www.npmjs.com/package/com-darryncampbell-cordova-plugin-intent.  Perhaps try uninstalling / re-installing the plugin (ensure to use the latest version).  Failing that, remove (& ensure it clears out) & re-add the Android platform

**Comment by mamcgree** [comment]
Sorry for confusion..
Your darryncampbell-cordova-plugin-intent has an import in the java code..
import com.darryncampbell.cordova.plugin.intent.api.exerciser.BuildConfig;

Do I have to install your exerciser program to use your intent plugin?

Thanks..

**Comment by darryncampbell** [comment]
Goodness!  I'm afraid I was over zealous with Android Studio's auto complete.  Sorry about that, should be fixed under https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/commit/6ef1a37ccd84db03712f4514c409d05f55fb5dd3 and 0.0.10
