### ISSUE TITLE
[Question] Register custom intent string

### ISSUE THREAD

**Issue by JaviRpo** [darryncampbell/darryncampbell-cordova-plugin-intent#68]
Hi @darryncampbell, I have a question for the next scenario.

i.e. 
when any app call the URL `tel:###....` the phone opens the *dialer* app
when any app call the URL `BEGIN:VCARD .....` the phone opens the *contacts* app

I want to create a specific string like `MyString: ...` and and I want my application to be called.

Can I use this plugin to register my app to open/receive a specific intent?

**Comment by darryncampbell** [comment]
Hi, in order to achieve that you would need to create an intent-filter(s) in your application manifest but that is not something this plugin will do for you.  This SO post may also help: https://stackoverflow.com/questions/28198983/ionic-cordova-add-intent-filter-using-config-xml

**Comment by darryncampbell** [comment]
presume resolved
