### ISSUE TITLE
Possible change

### ISSUE THREAD

**Issue by mamcgree** [darryncampbell/darryncampbell-cordova-plugin-intent#7]
Greetings Darryn..
Thanks for making changes so quickly.  May I make a suggestion.  Would it be possible to change your code on line 86 of IntentShim.java
File uriAsFile = new File(Environment.getExternalStorageDirectory(), fileName);
to
File uriAsFile = new File(uriAsString.replace("file://", "" ));

That way existing apk install intents would not have to change the file location.  Apparently this will create a valid file from an existing file:///path.

Thank you for your consideration.

**Comment by darryncampbell** [comment]
I don't think that would work, I may be wrong but the file provider will not accept file:// as the external storage directory even though the java file is created... I think it throws an exception when you create the provider

**Comment by mamcgree** [comment]
Hi darryn..
the uriAsString.replace("file://", "" ) removes the file:// from the beginning.. leaving /path...
I tested it and it works..  I am new to java so it took me all day to figure it out..  your solution was a good one but I am using cordova paths to download apk's so it would mean changing my locations 
Thanks..

**Comment by darryncampbell** [comment]
Ah I see! Yes that makes sense. I'll take a look at some point, I'd be concerned that '/' would not always be the correct directory (2 SD cards, adopted storage or some other corner case)... I'm not too sure but is worth looking into

**Comment by darryncampbell** [comment]
I couldn't get it to work with the path starting with a '/' but I made it possible to specify a path here: https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/blob/master/src/android/IntentShim.java#L91 as long as you specify file:/// to start the URI the rest of the path will be taken (e.g. https://github.com/darryncampbell/plugin-intent-api-exerciser/blob/master/www/js/index.js#L121).  As long as everything's in the shared storage.  Also added some more error logging if the file is not found or inaccessible.
