### ISSUE TITLE
Importing a Datawedge Profile

### ISSUE THREAD

**Issue by dbowmanDT** [darryncampbell/darryncampbell-cordova-plugin-intent#70]
My clients find the configuring of each device (of which there are many) to listen to my app. I notice there is a way to export a profile. Is there a way to import a profile using this plugin so that I can have my app import the profile. Then my users can just install my app and it is already setup to read barcodes?

**Comment by darryncampbell** [comment]
No but you could copy the profile to the auto-import directory (http://techdocs.zebra.com/datawedge/latest/guide/settings/#autoimport).  I wrote a community post on the subject (https://developer.zebra.com/community/home/blog/2018/08/10/mass-deploy-datawedge-profiles-with-auto-import) and there is a test app in Android & Xamarin (https://github.com/darryncampbell/DataWedgeAutoImport).  You should be able to achieve the same result using the Cordova file transfer plugin.  Just make sure the file permissions are set correctly, e.g. the sample app checks that here: https://github.com/darryncampbell/DataWedgeAutoImport/blob/master/Android/app/src/main/java/com/darryncampbell/datawedgeautoimport/MainActivity.java#L81

**Comment by darryncampbell** [comment]
Presume resolved
