### ISSUE TITLE
NOT getting any data with registerBroadcastReceiver ionic 3

### ISSUE THREAD

**Issue by azzaGarsaa** [darryncampbell/darryncampbell-cordova-plugin-intent#76]
i had followed the ZebraIonicDemo and i wanted to set it in in my app, so i  installed this plugin :  ionic cordova plugin remove com-darryncampbell-cordova-plugin-intent
which is now (1.1.7) 

`
(<any>window).plugins.intentShim.getIntent((intent) => {
          if (intent ) {
            console.log('intent', intent);
            (<any>window).plugins.intentShim.registerBroadcastReceiver({
              filterActions: [
                'com.continuousnet.myAPP.ACTION', 
   
              ]
            },
              function (intent) {
                //  Broadcast received
                console.log('Received Intent: ' + JSON.stringify(intent.extras));
              })
          }
        }, () => console.log("intent error"));

`

i'm not getting any data, even the  console.log('Received Intent: ' + JSON.stringify(intent.extras)); is not showing  
could any one help me ?

**Comment by darryncampbell** [comment]
Hi, does the ZebraIonicDemo work for you without modification?

**Comment by azzaGarsaa** [comment]
@darryncampbell  yes it's working

**Comment by darryncampbell** [comment]
Have you configured DataWedge to send intents to your application with the correct action?  See the ReadMe of ZebraIonicDemo for more information.

**Comment by azzaGarsaa** [comment]
@darryncampbell thank you for responding me, I found it:), in DataWedge configuration, it was Intent delivery should be set on Broadcast intent
