### ISSUE TITLE
Web Intent in PWA

### ISSUE THREAD

**Issue by haresh333** [darryncampbell/darryncampbell-cordova-plugin-intent#78]
I understand that current implementation of web intent can work only with IONIC APP.

is it possible to make it work in PWA? What are the limitations in making it available in PWA say as npm angular module instead of Cordova plugin

Does anyone have any implementation that can makes web intent work in PWA?

**Comment by darryncampbell** [comment]
Hi, I don't think that would be possible.  A PWA as no concept of native APIs or a plugin model does it?  So there would be no way to send & receive Android Intents.
