### ISSUE TITLE
Duplicate FileProviders issue

### ISSUE THREAD

**Issue by nikhiltyagi1991** [darryncampbell/darryncampbell-cordova-plugin-intent#8]
Hi,

I am facing the below error while building my app in android after installing this plugin.
Ionic 3 project.

> Element provider#android.support.v4.content.FileProvider at AndroidManifest.xml:49:9-51:20 duplicated with element declared at AndroidManifest.xml:33:9-35:20

AndroidManifest contains:-

```
<provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="android.support.v4.content.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" />
</provider>

<provider android:authorities="${applicationId}" android:exported="false" android:grantUriPermissions="true" android:name="android.support.v4.content.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths" />
</provider>
```

I think this might be because of clashing of some other native plugin. Here are the list of native plugins I am using:-

> com-darryncampbell-cordova-plugin-intent 0.0.10 "Intent Shim"
> com.megster.cordova.FileChooser 0.0.0 "File Chooser"
> cordova-base64-to-gallery 4.1.2 "base64ToGallery"
> cordova-plugin-camera 2.4.1 "Camera"
> cordova-plugin-camera-preview 0.9.0 "cordova-plugin-camera-preview"
> cordova-plugin-compat 1.1.0 "Compat"
> cordova-plugin-console 1.0.7 "Console"
> cordova-plugin-device 1.1.6 "Device"
> cordova-plugin-file 4.3.3 "File"
> cordova-plugin-file-transfer 1.6.3 "File Transfer"
> cordova-plugin-filepath 1.0.2 "FilePath"
> cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
> cordova-plugin-secure-storage 2.6.8 "SecureStorage"
> cordova-plugin-splashscreen 4.0.3 "Splashscreen"
> cordova-plugin-statusbar 2.2.3 "StatusBar"
> cordova-plugin-whitelist 1.3.2 "Whitelist"
> cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
> cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
> cordova.plugins.diagnostic 3.6.5 "Diagnostic"
> es6-promise-plugin 4.1.0 "Promise"
> info.protonet.imageresizer 0.1.1 "Image Resizer"
> ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
> ionic-plugin-keyboard 2.2.1 "Keyboard"

Please suggest a solution. Don't want to manually make builds after removing one provider.

**Comment by darryncampbell** [comment]
hmmm that's awkward, so you can't give two providers in the Android manifest, what if two different Cordova plugins want to use a provider?  The Plugin.xml reference here https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#edit-config describes merge conflicts but the only options are to put everything in a single plugin (not feasible here) or have one plugin's changes overwrite another (again, not feasible).  

The best solution for you might be to revert to version 0.0.7 of this plugin before I added the provider.

I'm curious which of your plugins are adding the other provider - I checked FileChooser but it is not that one.  Could you do a findInFiles and let me know?  Cheers.

**Comment by nikhiltyagi1991** [comment]
Thanks for immediate response. Dug a little deeper, it turns out the other provider is from cordova-plugin-camera.
Will try working with 0.0.7 version.

**Comment by darryncampbell** [comment]
Thanks, Camera is pretty ubiquitous!  Perhaps I should try and merge my paths into their XML or piggy-back on what Camera does somehow.  I'll leave this issue open until it's fixed properly but hopefully you can resolve your immediate issue by using 0.0.7
For my reference:
https://github.com/apache/cordova-plugin-camera/blob/master/plugin.xml
https://github.com/apache/cordova-plugin-camera/blob/master/src/android/xml/provider_paths.xml

**Comment by mamcgree** [comment]
Greetings...
I noticed on the camera plugin that they do not have mode="merge" in the config file.
That is probably what the problem is..
Cheers.

**Comment by darryncampbell** [comment]
I've addressed this in https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/commit/b32a2a495fbf4d44884623b547e37eb25b18bfec and added comments there but I also see this issue with other plugins which expose file providers e.g. https://github.com/kivra/cordova-plugin-remote-file-viewer.  I think it could be related to https://github.com/apache/cordova-plugin-camera/blob/master/plugin.xml#L88 defining provider_paths.xml as a source and not a resource file.  Anyway, in version 0.0.12 you should be able to use both plugins as long as you install the camera plugin first.
