### ISSUE TITLE
Web Intent - plugin_not_installed

### ISSUE THREAD

**Issue by weitaoyang** [darryncampbell/darryncampbell-cordova-plugin-intent#9]
(1)app.module.ts
providers:[WebIntent]

(2)package.json
"@ionic-native/web-intent": "3.10.2",

(3)config.xml
<plugin name="com-darryncampbell-cordova-plugin-intent" spec="https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent.git"/>

(4) after platform.ready().then(() => {}

global packages:

@ionic/cli-utils : 1.4.0
Cordova CLI      : 6.5.0
Ionic CLI        : 3.4.0
local packages:

@ionic/app-scripts              : 1.3.7
@ionic/cli-plugin-cordova       : 1.4.0
@ionic/cli-plugin-ionic-angular : 1.3.1
Cordova Platforms               : android 6.1.2
Ionic Framework                 : ionic-angular 3.3.0
System:

Node       : v6.11.0
OS         : Windows 7
Xcode      : not installed
ios-deploy : not installed
ios-sim    : not installed
npm        : 3.10.10

**Comment by darryncampbell** [comment]
This is not the WebIntent plugin, WebIntent was here https://github.com/phonegap/phonegap-plugins/tree/master/Android/WebIntent (now returning 404) but it is forked here: https://github.com/chrisekelley/cordova-webintent and that fork is still available.  You could rewrite your app to use this plugin or use the fork.

**Comment by karimabdelhakim** [comment]
i had this problem too,  so is there a method in this plugin similar to  [getUri()](https://ionicframework.com/docs/native/web-intent/#getUri)  or [getUri()](https://github.com/chrisekelley/cordova-webintent#geturi) ?

**Comment by darryncampbell** [comment]
If you call getIntent() it should be available in the returned JSON under the 'data' key (https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/blob/master/src/android/IntentShim.java#L462 ).  Will that work?  The getUri() you linked to returns Intent.getDataString() (https://github.com/chrisekelley/cordova-webintent/blob/master/src/android/WebIntent.java#L112) so if you need getDataString() instead it can be added - according to the docs getDataString() is just a String encoded URI but I have not tested it.

**Comment by karimabdelhakim** [comment]
i had same problem Web Intent - plugin_not_installed when using getIntent() but the problem was from ionic plugin itself and there is a workaround [here](https://github.com/ionic-team/ionic-native/issues/1609) for this problem , thanks anyway for your help

**Comment by darryncampbell** [comment]
Thanks for the link, interesting. Glad there is a workaround.
