### ISSUE TITLE
After install "ionic cordova plugin add com-darryncampbell-cordova-plugin-intent"

### ISSUE THREAD

**Issue by snaveenpandi** [darryncampbell/darryncampbell-cordova-plugin-intent#92]
After install "ionic cordova plugin add com-darryncampbell-cordova-plugin-intent" plugin app apk build failed 

I am using ionic version 3.20.0
cordova version  9.0.0 (cordova-lib@9.0.1)

E:\naveen\Test\saranya\platforms\android\app\src\main\java\com\ionicframework\cordova\webview\IonicWebViewEngine.java:11: error: package android.support.annotation does not exist
import android.support.annotation.RequiresApi;
                                 ^
E:\naveen\Test\saranya\platforms\android\app\src\main\java\com\ionicframework\cordova\webview\IonicWebViewEngine.java:122: error: cannot find symbol
    @RequiresApi(Build.VERSION_CODES.LOLLIPOP)
     ^
  symbol:   class RequiresApi
  location: class IonicWebViewEngine.ServerClient
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
> Task :app:compileDebugJavaWithJavac FAILED
24 actionable tasks: 6 executed, 18 up-to-date
E:\naveen\Test\saranya\platforms\android\gradlew: Command failed with exit code 1 Error output:
E:\naveen\Test\saranya\platforms\android\app\src\main\java\com\ionicframework\cordova\webview\IonicWebViewEngine.java:11: error: package android.support.annotation does not exist
import android.support.annotation.RequiresApi;
                                 ^
E:\naveen\Test\saranya\platforms\android\app\src\main\java\com\ionicframework\cordova\webview\IonicWebViewEngine.java:122: error: cannot find symbol
    @RequiresApi(Build.VERSION_CODES.LOLLIPOP)
     ^
  symbol:   class RequiresApi
  location: class IonicWebViewEngine.ServerClient
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
[ERROR] An error occurred while running cordova run android (exit code 1).

**Comment by darryncampbell** [comment]
Please try using version 1.3.0 of this plugin, I think the format is 

`ionic cordova plugin add com-darryncampbell-cordova-plugin-intent@1.3.0`

**Comment by snaveenpandi** [comment]
working fine,thnx

**Comment by abdullahMYMA** [comment]
> Please try using version 1.3.0 of this plugin, I think the format is
> 
> `ionic cordova plugin add com-darryncampbell-cordova-plugin-intent@1.3.0`

thanks bro its working fine
