### ISSUE TITLE
Android Support Libraries Missing

### ISSUE THREAD

**Issue by cabaird** [darryncampbell/darryncampbell-cordova-plugin-intent#93]
Hey Darryn,

First I want to thank you for being so attentive with this plugin.  It has been very helpful.  I was running into an issue with my builds when I tried on one of my apps without Androidx, installing your v1.3.0.  I was missing the old support libraries which are needed in some of your files.  I got past it as I happened to need it for my other files as well, so I added to my plugin.  But others who don't otherwise have these support libraries added will likely get errors.  I believe you should only need to add back the following to your `<platform name="android">` tag in your *plugin.xml*, which was recently removed, to solve it.

```
<framework src="com.android.support:support-v4:27.1.0" />
```
 Take a look at it and let me know what you think.

FYI, I am trying to make a switch to using https://github.com/dpa99c/cordova-plugin-androidx-adapter to cover these and all other androidx support cases if I can, so yours and other plugins that don't need to be updated don't have to.

**Comment by darryncampbell** [comment]
Hi @cabaird , I am looking at the plugin.xml source code for v1.3.0 and it looks like that framework line *is already present*.  Am I missing something?

https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/blob/160def5f8698f24d5ad83cb0d5b1ff6f60911f96/plugin.xml#L42

**Comment by cabaird** [comment]
Nope.  Apparently I'm the one that's missing something.  I'm not sure what I was looking at.  My apologies.  Maybe I'm having issues with mismatching versions of these or something.
